jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Botchla\JiraBundle\Security\User\JiraUser:
            algorithm: plaintext
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        jira:
            id: jira_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            security: true
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /login
